language: minimal

git:
  depth: false # Accepts false or any number representing the commit count, defaults to 50
  autocrlf: input # Prevents git to try to be smart with line endings

os:
  - linux
  - osx
  - windows

env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git" # Convenience variable for shortening commands
    - GRAVIS="$HOME/gravis" # Convenience variable for shortening commands
    - TERM="dumb" # Prevents "smart" output from Gradle
  matrix:
    - JDK="adopt@"
    - JDK="adopt@1.11"
    - JDK="adopt-openj9@"
    - JDK="adopt-openj9@1.11"

jobs:
  include: # Add a job with default OS and the specified matrix environment
    env:
      - JDK="adopt@1.8" 
  exclude: # Excludes builds with OSX and OpenJ9
    - os: osx
      env:
        - JDK="adopt-openj9@"
    - os: osx
      env:
        - JDK="adopt-openj9@1.11"

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS # Check out the script set
  - source $GRAVIS/install-jdk # Install the JDK you configured in the $JDK environment variable

script:
  - travis_retry ./gradlew check
