_reference_jdk: &reference_jdk
  'JDK="adopt@1.11.0"'
_reference_os: &reference_os
  'linux'

language: minimal

git:
  depth: false # Accepts false or any number representing the commit count, defaults to 50
  autocrlf: input # Prevents git to try to be smart with line endings

os:
  - linux
  - osx
  - windows

env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git" # Convenience variable for shortening commands
    - GRAVIS="$HOME/gravis" # Convenience variable for shortening commands
    - TERM="dumb" # Prevents "smart" output from Gradle
  matrix:
    - JDK="adopt@"
    - *reference_jdk
    - JDK="adopt-openj9@"
    - JDK="adopt-openj9@1.11"

stages:
  - check # This is for running the stage before test
  - test
  - name: deploy
    # Disable Deploy for PRs
    if: repo = DanySK/Plugin-CI-Running-Example

_check_job: &check_job
  stage: check
  os: *reference_os
  env: *reference_jdk

_linux_workspace: &linux_workspace
  'build-workspace'

jobs:
  include: # Add a job with default OS and the specified matrix environment
    - <<: *check_job # YAML merge key: inserts the map found at this anchor
      script: ./gradlew check # Overrides the default settings
      workspaces:
        create: # Save the work for later use
          name: *linux_workspace
          paths: "${TRAVIS_BUILD_DIR}"
    - stage: deploy
      install:
        - openssl aes-256-cbc -K $encrypted_f778b2e1574b_key -iv $encrypted_f778b2e1574b_iv -in secrets.asc.enc -out secrets.asc -d
      script: # This overrides the default settings
        - echo Deploy! # Problem: we need to pass credentials...
      workspaces: # Reuse the work done in the initial phase
        use: *linux_workspace
  exclude: # No need to re-run the tests we performed in the first stage
    - <<: *check_job
      stage: test # override value of 'stage'

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS # Check out the script set
  - source $GRAVIS/install-jdk # Install the JDK you configured in the $JDK environment variable

script:
  - travis_retry ./gradlew test # by default, just test. Deep check only on the reference build
